-- Legacy PostgreSQL schema; NOT the active application database.
-- No demo credentials or direct browser access are provisioned.
BEGIN;
-- 1. Hamkorlar jadvali (Partners)
CREATE TABLE IF NOT EXISTS partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  category TEXT NOT NULL,
  hours TEXT NOT NULL,
  region TEXT NOT NULL,
  price BIGINT NOT NULL DEFAULT 0,
  contract_status TEXT NOT NULL DEFAULT 'active' CHECK (contract_status IN ('active', 'pending', 'expired')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Foydalanuvchilar jadvali (Users)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('client', 'operator', 'director', 'partner')),
  partner_id BIGINT REFERENCES partners(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Murojaatlar jadvali (Cases)
CREATE TABLE IF NOT EXISTS cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT UNIQUE,
  client_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  region TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  preferred_time TEXT NOT NULL DEFAULT 'Istalgan vaqt',
  status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'reviewing', 'searching', 'arranging', 'contacted', 'completed', 'cancelled')),
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'urgent')),
  coordinator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  due_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  tracking_token TEXT NOT NULL,
  consent_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Murojaat ichidagi xizmatlar (Services)
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  partner_id BIGINT REFERENCES partners(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'contacted', 'delivered', 'completed', 'cancelled')),
  price BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tarix va audit (History)
CREATE TABLE IF NOT EXISTS history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  message TEXT NOT NULL,
  actor_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Biriktirilgan fayllar (Attachments)
CREATE TABLE IF NOT EXISTS attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  size BIGINT NOT NULL,
  data TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Baholash va sharhlar (Feedback)
CREATE TABLE IF NOT EXISTS feedback (
  case_id BIGINT PRIMARY KEY REFERENCES cases(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Oila paketlari (Packages)
CREATE TABLE IF NOT EXISTS packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  tier TEXT NOT NULL CHECK (tier IN ('Start', 'Komfort', 'Premium')),
  expires_at TIMESTAMPTZ NOT NULL,
  service_limit INT NOT NULL CHECK (service_limit > 0),
  members JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Paketdan foydalanish hisobi (Package Usage)
CREATE TABLE IF NOT EXISTS package_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  case_id BIGINT NOT NULL UNIQUE REFERENCES cases(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Bildirishnomalar navbati (Notifications)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  event TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'telegram',
  status TEXT NOT NULL DEFAULT 'queued',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  recipient_phone TEXT,
  message TEXT
);

-- Indekslar
CREATE INDEX IF NOT EXISTS idx_cases_client_id ON cases(client_id);
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_services_case_id ON services(case_id);
CREATE INDEX IF NOT EXISTS idx_services_partner_id ON services(partner_id);
CREATE INDEX IF NOT EXISTS idx_history_case_id ON history(case_id);

-- Close direct browser access to legacy application tables.
-- Run manually in Supabase SQL Editor if an earlier permissive script was used.
-- No rows are changed or deleted. The application now uses Node.js + SQLite.

DO $$
DECLARE
  t text;
  p record;
BEGIN
  FOREACH t IN ARRAY ARRAY['partners', 'users', 'cases', 'services', 'history',
    'attachments', 'feedback', 'packages', 'package_usage', 'notifications'] LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
      FOR p IN SELECT policyname FROM pg_policies
        WHERE schemaname = 'public' AND tablename = t LOOP
        EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, t);
      END LOOP;
      EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated', t);
    END IF;
  END LOOP;
END $$;


COMMIT;
