-- ========================================================
-- ZARURIYAT — Supabase (PostgreSQL) To'liq Baza Sxemasi
-- Ushbu faylni Supabase -> SQL Editor'ga tashlang va RUN tugmasini bosing!
-- ========================================================

-- 1. Hamkorlar jadvali (Partners)
CREATE TABLE IF NOT EXISTS partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  category TEXT NOT NULL,
  hours TEXT NOT NULL,
  region TEXT NOT NULL,
  price BIGINT NOT NULL DEFAULT 0,
  contract_status TEXT NOT NULL DEFAULT 'active' CHECK (contract_status IN ('active', 'pending', 'expired')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Foydalanuvchilar jadvali (Users)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('client', 'operator', 'director', 'partner')),
  partner_id BIGINT REFERENCES partners(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Murojaatlar jadvali (Cases)
CREATE TABLE IF NOT EXISTS cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT UNIQUE,
  client_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  region TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  preferred_time TEXT NOT NULL DEFAULT 'Istalgan vaqt',
  status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'reviewing', 'searching', 'arranging', 'contacted', 'completed', 'cancelled')),
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'urgent')),
  coordinator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  due_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  tracking_token TEXT NOT NULL,
  consent_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Murojaat ichidagi xizmatlar (Services)
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  partner_id BIGINT REFERENCES partners(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'contacted', 'delivered', 'completed', 'cancelled')),
  price BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tarix va audit (History)
CREATE TABLE IF NOT EXISTS history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  message TEXT NOT NULL,
  actor_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Biriktirilgan fayllar (Attachments)
CREATE TABLE IF NOT EXISTS attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  size BIGINT NOT NULL,
  data TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Baholash va sharhlar (Feedback)
CREATE TABLE IF NOT EXISTS feedback (
  case_id BIGINT PRIMARY KEY REFERENCES cases(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Oila paketlari (Packages)
CREATE TABLE IF NOT EXISTS packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  tier TEXT NOT NULL CHECK (tier IN ('Start', 'Komfort', 'Premium')),
  expires_at TIMESTAMPTZ NOT NULL,
  service_limit INT NOT NULL CHECK (service_limit > 0),
  members JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Paketdan foydalanish hisobi (Package Usage)
CREATE TABLE IF NOT EXISTS package_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  case_id BIGINT NOT NULL UNIQUE REFERENCES cases(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Bildirishnomalar navbati (Notifications)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  event TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'telegram',
  status TEXT NOT NULL DEFAULT 'queued',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  recipient_phone TEXT,
  message TEXT
);

-- Indekslar
CREATE INDEX IF NOT EXISTS idx_cases_client_id ON cases(client_id);
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_services_case_id ON services(case_id);
CREATE INDEX IF NOT EXISTS idx_services_partner_id ON services(partner_id);
CREATE INDEX IF NOT EXISTS idx_history_case_id ON history(case_id);

-- RLS (Row Level Security) ni o'chirish — frontend bemalol to'g'ridan-to'g'ri o'qib-yozishi uchun
ALTER TABLE partners DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE services DISABLE ROW LEVEL SECURITY;
ALTER TABLE history DISABLE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- anon va authenticated rollariga ruxsat berish
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

-- Namunaviy ma'lumotlar (Boshlang'ich hisoblar)
INSERT INTO partners (id, name, phone, address, category, hours, region, price, contract_status) VALUES
(1, '«Adolat» yuridik byurosi', '+998901112233', 'Toshkent sh., Amir Temur shox ko‘chasi, 12-uy', 'legal', '09:00 - 18:00', 'Toshkent shahri', 150000, 'active')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (login, name, phone, password_hash, role, partner_id) VALUES
('operator', 'Operator Sarvinoz', '+998901234501', 'Zaruriyat2026!', 'operator', NULL),
('director', 'Rahbar Aziz', '+998901234502', 'Zaruriyat2026!', 'director', NULL),
('client', 'Mijoz Dilshod', '+998901234503', 'Zaruriyat2026!', 'client', NULL),
('partner', 'Hamkor Rustam', '+998901234504', 'Zaruriyat2026!', 'partner', 1)
ON CONFLICT (login) DO UPDATE SET password_hash = 'Zaruriyat2026!';
