-- Stage 2. Apply once in Supabase SQL Editor, then set FEATURE_STAGE2=true.
-- Preserves accounts, case records and passwords. Does not enable SMS or Telegram.
BEGIN;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS blocked_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_verified_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS telegram_chat_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_telegram_chat ON public.users(telegram_chat_id) WHERE telegram_chat_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS public.otp_challenges (
 id TEXT PRIMARY KEY CHECK(length(id)=64), user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 purpose TEXT NOT NULL CHECK(purpose IN ('verify','reset')), code_hash TEXT NOT NULL CHECK(length(code_hash)=64),
 attempts INTEGER NOT NULL DEFAULT 0, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_otp_user_purpose ON public.otp_challenges(user_id,purpose,created_at);
CREATE TABLE IF NOT EXISTS public.telegram_links (
 token_hash TEXT PRIMARY KEY CHECK(length(token_hash)=64),user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL,consumed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.account_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_id BIGINT REFERENCES public.users(id),
 target_id BIGINT REFERENCES public.users(id),action TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS claim_token TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS provider_message_id BIGINT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_notifications_delivery ON public.notifications(status,next_attempt_at);

DO $$ DECLARE t TEXT; BEGIN
 FOREACH t IN ARRAY ARRAY['otp_challenges','telegram_links','account_audit'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM anon,authenticated',t);
  EXECUTE format('GRANT ALL ON public.%I TO service_role',t);
 END LOOP;
END $$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.zar_login(p_login TEXT,p_password TEXT)
RETURNS JSONB LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE u users; BEGIN
 SELECT * INTO u FROM users WHERE login=p_login OR regexp_replace(phone,'[[:space:]()-]','','g')=p_login LIMIT 1;
 IF u.id IS NULL OR u.blocked_at IS NOT NULL OR u.password_hash !~ '^\$2[ab]\$' THEN RETURN NULL; END IF;
 IF u.password_hash IS DISTINCT FROM extensions.crypt(p_password,u.password_hash) THEN RETURN NULL; END IF;
 RETURN to_jsonb(u)-'password_hash'-'telegram_chat_id';
END $$;

CREATE OR REPLACE FUNCTION public.zar_start_otp(p_phone TEXT,p_purpose TEXT,p_user_id BIGINT,p_code_hash TEXT,p_id TEXT)
RETURNS JSONB LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE u users; BEGIN
 IF p_purpose NOT IN ('verify','reset') OR length(p_code_hash)<>64 OR length(p_id)<>64 THEN RAISE EXCEPTION 'So‘rov noto‘g‘ri.'; END IF;
 SELECT * INTO u FROM users WHERE regexp_replace(phone,'[[:space:]()-]','','g')=p_phone AND blocked_at IS NULL LIMIT 1 FOR UPDATE;
 IF u.id IS NULL THEN RETURN NULL; END IF;
 IF p_purpose='verify' AND u.id IS DISTINCT FROM p_user_id THEN RETURN NULL; END IF;
 -- Reset is available only after actual phone ownership was previously verified.
 IF p_purpose='reset' AND u.phone_verified_at IS NULL THEN RETURN NULL; END IF;
 UPDATE otp_challenges SET consumed_at=now() WHERE user_id=u.id AND purpose=p_purpose AND consumed_at IS NULL;
 INSERT INTO otp_challenges(id,user_id,purpose,code_hash,expires_at) VALUES(p_id,u.id,p_purpose,p_code_hash,now()+interval '10 minutes');
 RETURN jsonb_build_object('phone',p_phone);
END $$;

CREATE OR REPLACE FUNCTION public.zar_confirm_otp(p_id TEXT,p_code_hash TEXT,p_purpose TEXT,p_user_id BIGINT,p_password_hash TEXT)
RETURNS JSONB LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE challenge otp_challenges; u users; uid BIGINT; BEGIN
 SELECT user_id INTO uid FROM otp_challenges WHERE id=p_id;
 SELECT * INTO u FROM users WHERE id=uid AND blocked_at IS NULL FOR UPDATE;
 IF u.id IS NULL THEN RETURN jsonb_build_object('ok',false); END IF;
 SELECT * INTO challenge FROM otp_challenges WHERE id=p_id FOR UPDATE;
 IF challenge.id IS NULL OR challenge.consumed_at IS NOT NULL OR challenge.expires_at<=now() OR challenge.attempts>=5 OR challenge.purpose<>p_purpose THEN RETURN jsonb_build_object('ok',false); END IF;
 IF challenge.user_id IS DISTINCT FROM u.id OR (p_purpose='verify' AND u.id IS DISTINCT FROM p_user_id) THEN RETURN jsonb_build_object('ok',false); END IF;
 UPDATE otp_challenges SET attempts=attempts+1 WHERE id=p_id;
 -- Return instead of raising, so failed attempt counters are committed.
 IF challenge.code_hash IS DISTINCT FROM p_code_hash THEN RETURN jsonb_build_object('ok',false); END IF;
 IF p_purpose='reset' THEN
  IF p_password_hash IS NULL OR p_password_hash !~ '^\$2a\$[0-9]{2}\$[./A-Za-z0-9]{53}$' THEN RETURN jsonb_build_object('ok',false); END IF;
  UPDATE users SET password_hash=p_password_hash WHERE id=u.id;
  DELETE FROM sessions WHERE user_id=u.id;
 ELSE
  UPDATE users SET phone_verified_at=now() WHERE id=u.id;
 END IF;
 UPDATE otp_challenges SET consumed_at=now() WHERE id=p_id;
 INSERT INTO account_audit(target_id,action) VALUES(u.id,CASE p_purpose WHEN 'reset' THEN 'password.reset' ELSE 'phone.verified' END);
 RETURN jsonb_build_object('ok',true);
END $$;

CREATE OR REPLACE FUNCTION public.zar_bind_telegram(p_token_hash TEXT,p_chat_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE link telegram_links; BEGIN
 SELECT * INTO link FROM telegram_links WHERE token_hash=p_token_hash AND consumed_at IS NULL AND expires_at>now() FOR UPDATE;
 IF link.token_hash IS NULL OR p_chat_id<=0 OR NOT EXISTS(SELECT 1 FROM users WHERE id=link.user_id AND blocked_at IS NULL) THEN RETURN false; END IF;
 IF EXISTS(SELECT 1 FROM users WHERE telegram_chat_id=p_chat_id AND id<>link.user_id) THEN RETURN false; END IF;
 UPDATE users SET telegram_chat_id=p_chat_id WHERE id=link.user_id AND blocked_at IS NULL;
 IF NOT FOUND THEN RETURN false; END IF;
 UPDATE telegram_links SET consumed_at=now() WHERE token_hash=p_token_hash;
 INSERT INTO account_audit(target_id,action) VALUES(link.user_id,'telegram.linked');
 RETURN true;
END $$;

CREATE OR REPLACE FUNCTION public.zar_unlink_telegram(p_chat_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE uid BIGINT; BEGIN
 UPDATE users SET telegram_chat_id=NULL WHERE telegram_chat_id=p_chat_id RETURNING id INTO uid;
 IF uid IS NOT NULL THEN
  UPDATE notifications SET status='suppressed',claim_token=NULL,lease_until=NULL WHERE case_id IN (SELECT id FROM cases WHERE client_id=uid) AND status IN ('queued','failed','sending');
  INSERT INTO account_audit(target_id,action) VALUES(uid,'telegram.unlinked');
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.zar_claim_notifications(p_claim_token TEXT)
RETURNS JSONB LANGUAGE sql SET search_path=public,extensions,pg_temp AS $$
 WITH candidates AS (
  SELECT n.id FROM notifications n JOIN cases c ON c.id=n.case_id JOIN users u ON u.id=c.client_id
  WHERE u.blocked_at IS NULL AND u.telegram_chat_id IS NOT NULL AND n.attempts<5 AND n.next_attempt_at<=now()
   AND (n.status IN ('queued','failed') OR (n.status='sending' AND n.lease_until<now()))
  ORDER BY n.id LIMIT 10 FOR UPDATE OF n SKIP LOCKED
 ), claimed AS (
  UPDATE notifications n SET status='sending',attempts=attempts+1,lease_until=now()+interval '2 minutes',claim_token=p_claim_token
  FROM candidates q WHERE n.id=q.id RETURNING n.id,n.case_id,n.event,n.attempts
 ) SELECT coalesce(jsonb_agg(jsonb_build_object('id',n.id,'event',n.event,'attempts',n.attempts,'caseNumber',c.number,'caseStatus',c.status,'chatId',u.telegram_chat_id)),'[]'::jsonb)
 FROM claimed n JOIN cases c ON c.id=n.case_id JOIN users u ON u.id=c.client_id;
$$;

CREATE OR REPLACE FUNCTION public.zar_finish_notification(p_id BIGINT,p_claim_token TEXT,p_sent BOOLEAN,p_provider_id BIGINT,p_error TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE changed BIGINT; BEGIN
 UPDATE notifications SET status=CASE WHEN p_sent THEN 'sent' ELSE 'failed' END,
  sent_at=CASE WHEN p_sent THEN now() ELSE NULL END,provider_message_id=p_provider_id,last_error=left(p_error,200),
  next_attempt_at=now()+make_interval(secs=>least(3600,(power(2,attempts)*60)::INT)),claim_token=NULL,lease_until=NULL
 WHERE id=p_id AND claim_token=p_claim_token AND status='sending' RETURNING id INTO changed;
 RETURN changed IS NOT NULL;
END $$;

CREATE OR REPLACE FUNCTION public.zar_set_block(p_actor_id BIGINT,p_target_id BIGINT,p_blocked BOOLEAN)
RETURNS VOID LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM users WHERE id=p_actor_id AND role='director' AND blocked_at IS NULL) OR p_actor_id=p_target_id THEN RAISE EXCEPTION 'Ruxsat yo‘q.'; END IF;
 IF NOT EXISTS(SELECT 1 FROM users WHERE id=p_target_id AND role<>'director') THEN RAISE EXCEPTION 'Hisob topilmadi.'; END IF;
 UPDATE users SET blocked_at=CASE WHEN p_blocked THEN now() ELSE NULL END WHERE id=p_target_id;
 IF p_blocked THEN DELETE FROM sessions WHERE user_id=p_target_id;UPDATE otp_challenges SET consumed_at=now() WHERE user_id=p_target_id AND consumed_at IS NULL; END IF;
 INSERT INTO account_audit(actor_id,target_id,action) VALUES(p_actor_id,p_target_id,CASE WHEN p_blocked THEN 'account.blocked' ELSE 'account.unblocked' END);
END $$;

DO $$ DECLARE f RECORD; BEGIN
 FOR f IN SELECT p.oid::regprocedure AS signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE 'zar_%' LOOP
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',f.signature);
  EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role',f.signature);
 END LOOP;
END $$;
NOTIFY pgrst,'reload schema';
COMMIT;
